### PR TITLE
Image bounds

### PR DESCRIPTION
**Pull request by B-LechCode**
Implemented a possible fix for #255 

Default mode is preserved as is, I added a new mode for the image geometry, which limits the area for the image to the available area.

Had to reduce the maximum file name char count from 20 to 18, otherwise the left panel unintentionally changes with by varying file name lengths.

### CODE REVIEW

**Comment by B-LechCode** [comment]
Hi @woelper,

I discovered a little problem: the width of the path string is sometimes too wide for the panel width.
Do you know a convenient method to estimate the strings rendered width?
I think, going for a uniform width string isn't a good idea from a design point of view, is it?

Thank you :)

**Comment by woelper** [comment]
I have a couple of thoughts, but no good solution either:
Egui provides an overflow character which you can try at https://www.egui.rs/ in the "Text Layout" demo.
I think calling truncate (https://docs.rs/egui/latest/egui/widgets/struct.Label.html#method.truncate) on a label could be a way to start.

My suggestion would be to let egui handle the layout completely and get the width of the available size with `ctx.available_rect()` after the panels have been added for example. I have not tried it, but the docs look like this may be the only info you need perhaps:
https://docs.rs/egui/latest/egui/struct.Context.html#method.available_rect

**Comment by B-LechCode** [comment]
Using available_rect for calculation of the image dimensions is what I did, but only once after the image is reset, to allow dragging and zooming. In the case of an overflowing text, the left panel expands afterwards. A possible fix could be: calculating this twice, but in my opinion it's not good either, it's better to directly target the problem's source.
Using truncate would be possible, but in my opinion somehow ugly, because of truncating the string on "both sides". What do you think about that?

I found this, but didn't understand how to implement yet: https://github.com/emilk/egui/discussions/1488
If this would work, I could iterate the "front" string truncation until it fits. Having a fixed width panel when browsing images is the best approach, I think.

**Comment by woelper** [comment]
> Using available_rect for calculation of the image dimensions is what I did, but only once after the image is reset, to allow dragging and zooming. In the case of an overflowing text, the left panel expands afterwards, while rendering, I think. A possible fix could be: calculating this twice, but in my opinion it's not good either, it's better to directly target the problem's source. Using truncate would be possible, but in my opinion somehow ugly, because of truncating the string on "both sides". What do you think about that?
> 
> I found this, but didn't understand how to implement yet: [emilk/egui#1488](https://github.com/emilk/egui/discussions/1488) If this would work, I could iterate the "front" string truncation until it fits. Having a fixed width panel when browsing images is the best approach, I think.

I _think_ they talk about layouting the text in a separate step before painting it, and then using the layout information to get the length.

I am not sure I understand what you mean by "truncating on both sides". Would it not be possible to omit the "rightmost" part of the filename?

**Comment by B-LechCode** [comment]
It is indeed possible to omit the rightmost part of the filename, but I don't think it's pretty, truncating the leftmost part only seems better. I implemented rightmost truncation it in my last commit, please have a look :)

**Comment by woelper** [comment]
Closing this as addressed by https://github.com/woelper/oculante/pull/267 - thanks a bunch!

**Pull request closed without merging**
