### PR TITLE
Compare improvements

### PR DESCRIPTION
**Pull request by woelper**

### CODE REVIEW

**Comment by Stoppedpuma** [comment]
@woelper Small oversight, `ClearImage` isn't registered and doesn't appear in the shortcuts list.

`ERROR oculante::shortcuts] Command not registered: 'ClearImage'. Inserting new.`

**Comment by woelper** [comment]
The error itself is expected, this happens if your configuration does not have a value that has been added to Oculante. If it is missing in the shortcuts list, this of course sounds like a bug!

**Comment by Stoppedpuma** [comment]
Yep, missing in the shortcut list.

**Comment by woelper** [comment]
This is fixed in master now.

**Comment by Stoppedpuma** [comment]
@woelper This now causes all images to clear instead of just the current one.

**Pull request merged**
