### PR TITLE
parse uri paths given in input

### PR DESCRIPTION
**Pull request by diegostafa**
currently oculante can't read an input in a URI format (file:///this/is/a/valid/file)

i've added fluent_uri as a dependency to extract the path before mapping it into a PathBuf

### CODE REVIEW

**Comment by woelper** [comment]
Thanks!
Could this also be relevant in other scenarios, such as a dropped file?

**Comment by diegostafa** [comment]
i can't find a program exposing a uri when dragging a file, i don't know if Event::Drop(file) would even fire in that case

**Review by woelper — APPROVED** [review]

**Comment by woelper** [comment]
Thank you!

**Comment by woelper** [comment]
Unfortunately this broke the ability to open files on Windows. I disabled this on windows:
https://github.com/woelper/oculante/pull/295

**Pull request merged**
