### PR TITLE
Shaderc

### PR DESCRIPTION
**Pull request by woelper**
Enable using `shaderc` or `glsl-to-spirv`. 

The features are `spirv` and `shaderc` with `spirv` being the default. You can build a custom version of oculante using `shaderc` with `cargo build --release --features shaderc` for example.

### CODE REVIEW

**Comment by yurivict** [comment]
@woelper 
It still builds glsl-to-spirv-0.1.7 and fails when the feature shaderc is enabled.

**Comment by woelper** [comment]
How exactly does it fail? Could you provide the error please?

**Comment by yurivict** [comment]
```
  In file included from /usr/ports/graphics/oculante/work/oculante-0.8.21-20-g9062c5f/cargo-crates/glsl-to-spirv-0.1.7/glslang/hlsl/hlslScanContext.cpp:45:
  In file included from /usr/ports/graphics/oculante/work/oculante-0.8.21-20-g9062c5f/cargo-crates/glsl-to-spirv-0.1.7/glslang/hlsl/../glslang/Include/Types.h:41:
  In file included from /usr/ports/graphics/oculante/work/oculante-0.8.21-20-g9062c5f/cargo-crates/glsl-to-spirv-0.1.7/glslang/hlsl/../glslang/Include/../Include/Common.h:99:
  /usr/ports/graphics/oculante/work/oculante-0.8.21-20-g9062c5f/cargo-crates/glsl-to-spirv-0.1.7/glslang/hlsl/../glslang/Include/../Include/PoolAlloc.h:314:54: error: 'operator=' is a private member of 'glslang::TPoolAllocator'
    314 |     void setAllocator(TPoolAllocator* a) { allocator = *a; }
        |                                            ~~~~~~~~~ ^ ~~
  /usr/ports/graphics/oculante/work/oculante-0.8.21-20-g9062c5f/cargo-crates/glsl-to-spirv-0.1.7/glslang/hlsl/../glslang/Include/../Include/PoolAlloc.h:244:21: note: declared private here
    244 |     TPoolAllocator& operator=(const TPoolAllocator&);  // don't allow assignment operator
        |                     ^
```

**Comment by woelper** [comment]
This was due to a configuration problem on my end. On latest master, you should be able to build with

`cargo build --no-default-features  --features notan/shaderc` and it should not pull in `glsl-to-spirv`.

**Comment by yurivict** [comment]
```cargo build --no-default-features  --features notan/shaderc``` fails:
```
error[E0599]: no variant or associated item named `get_mouse_position` found for enum `mouse_position::mouse_position::Mouse` in the current scope
    --> src/ui.rs:2181:35
     |
2181 |             let position = Mouse::get_mouse_position();
     |                                   ^^^^^^^^^^^^^^^^^^ variant or associated item not found in `Mouse`

```

**Pull request merged**
